/**
 * Next's own declarations for importing an image as a module.
 *
 * These normally arrive through `next-env.d.ts`, which is generated by `next
 * dev` and `next build` and is gitignored — so on a machine that has run
 * either, `tsc` sees them and a static image import type-checks. CI has run
 * neither: `npm run verify` type-checks *before* it builds, and a fresh
 * checkout has no `next-env.d.ts` at all. The first static image import in the
 * codebase therefore passed every local gate and failed in CI with
 * `TS2307: Cannot find module '…/captivate-icon.png'`.
 *
 * This is a reference to Next's own types rather than a copy of them, and it
 * is committed, so the gate does not depend on a generated file having been
 * generated. Deleting it as a duplicate of `next-env.d.ts` reopens the hole.
 */

/// <reference types="next/image-types/global" />
