"use server";

import { z } from "zod";
import { revalidatePath } from "next/cache";
import { supabaseServer } from "@/lib/supabase/server";
import { STORAGE_BUCKETS } from "@/lib/supabase/config";
import {
  fetchImageBytes,
  storeSourcedImage,
  IMAGE_COST_ESTIMATE_USD,
} from "@/lib/ai/visual-sourcing";
import type { AssetResult } from "./assets";

/**
 * Committing a searched or generated image.
 *
 * The result of a search is a URL on someone else's CDN and the result of a
 * generation is a preview in memory; neither is an asset until the author says
 * so. When they do, the *server* fetches and re-hosts the bytes, because every
 * other image in Captivate is served from its own private storage through a
 * signed URL, and a permanent hotlink into a provider's CDN would be the one
 * picture in a deck that stops working a year from now.
 *
 * The fetch is a real boundary rather than a convenience: host allowlist, byte
 * ceiling enforced while reading, and the format taken from the bytes rather
 * than from the provider's headers. See `visual-sourcing.ts`.
 */

const StockInput = z.object({
  fullUrl: z.url(),
  providerAssetId: z.string().max(120),
  originalPageUrl: z.url(),
  creatorName: z.string().max(200),
  creatorPageUrl: z.url(),
  licenseRef: z.string().max(120),
  altText: z.string().max(600).default(""),
  presentationId: z.string().uuid().nullable().optional(),
});

const GeneratedInput = z.object({
  /** The generated bytes, as the preview data URL the browser was shown. */
  dataUrl: z.string().max(30_000_000).startsWith("data:image/"),
  prompt: z.string().max(1000),
  model: z.string().max(120),
  quality: z.string().max(40),
  generationMs: z.number().int().min(0).max(600_000),
  altText: z.string().max(600).default(""),
  presentationId: z.string().uuid().nullable().optional(),
});

const INGEST_MESSAGES: Record<string, string> = {
  "host-not-allowed": "That image isn't from a source this deployment fetches from.",
  unreachable: "Couldn't fetch that image. Nothing was saved.",
  "too-large": "That image is larger than the upload limit.",
  "not-an-image": "That file isn't an image, whatever it claims to be.",
  storage: "Couldn't save the image. Nothing was changed.",
};

const say = (code: string) => INGEST_MESSAGES[code] ?? "Couldn't save that image.";

/** Re-hosts a chosen stock photo and records who took it and under what terms. */
export async function saveStockPhoto(
  input: unknown,
): Promise<AssetResult<{ id: string; url: string }>> {
  const parsed = StockInput.safeParse(input);
  if (!parsed.success) return { ok: false, error: "That image couldn't be saved." };

  const fetched = await fetchImageBytes(parsed.data.fullUrl);
  if (!fetched.ok) return { ok: false, error: say(fetched.error) };

  const stored = await storeSourcedImage(fetched.data);
  if (!stored.ok) return { ok: false, error: say(stored.error) };

  return insertSourced(stored.data.storagePath, fetched.data.mimeType, fetched.data.bytes.length, {
    presentation_id: parsed.data.presentationId ?? null,
    alt_text: parsed.data.altText,
    original_filename: `${parsed.data.creatorName} on Pexels`,
    source: "stock",
    provider: "pexels",
    provider_asset_id: parsed.data.providerAssetId,
    original_page_url: parsed.data.originalPageUrl,
    creator_name: parsed.data.creatorName,
    creator_page_url: parsed.data.creatorPageUrl,
    license_ref: parsed.data.licenseRef,
    // When these terms were last confirmed against the provider, so a future
    // licence change has something to check existing rows against.
    verified_at: new Date().toISOString(),
  });
}

/** Stores an accepted generated image with the prompt and model that made it. */
export async function saveGeneratedImage(
  input: unknown,
): Promise<AssetResult<{ id: string; url: string }>> {
  const parsed = GeneratedInput.safeParse(input);
  if (!parsed.success) return { ok: false, error: "That image couldn't be saved." };

  const comma = parsed.data.dataUrl.indexOf(",");
  const header = parsed.data.dataUrl.slice(5, comma);
  if (comma < 0 || !header.endsWith(";base64")) {
    return { ok: false, error: "That image couldn't be read." };
  }

  let bytes: Uint8Array;
  try {
    bytes = Uint8Array.from(Buffer.from(parsed.data.dataUrl.slice(comma + 1), "base64"));
  } catch {
    return { ok: false, error: "That image couldn't be read." };
  }
  // The same check the fetched path applies: what the browser sent back is a
  // claim until the bytes agree with it.
  const isPng = bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47;
  if (!isPng) return { ok: false, error: "That file isn't an image, whatever it claims to be." };

  const stored = await storeSourcedImage({ bytes, mimeType: "image/png", extension: "png" });
  if (!stored.ok) return { ok: false, error: say(stored.error) };

  return insertSourced(stored.data.storagePath, "image/png", bytes.length, {
    presentation_id: parsed.data.presentationId ?? null,
    alt_text: parsed.data.altText,
    original_filename: parsed.data.prompt.slice(0, 200),
    source: "generated",
    provider: "openai",
    model: parsed.data.model,
    prompt: parsed.data.prompt,
    quality: parsed.data.quality,
    generation_ms: parsed.data.generationMs,
  });
}

async function insertSourced(
  storagePath: string,
  mimeType: string,
  byteSize: number,
  provenance: Record<string, unknown>,
): Promise<AssetResult<{ id: string; url: string }>> {
  const supabase = await supabaseServer();
  const { data, error } = await supabase
    .from("assets")
    .insert({ storage_path: storagePath, mime_type: mimeType, byte_size: byteSize, kind: "image", ...provenance } as never)
    .select("id")
    .single();

  if (error || !data) {
    // Orphaned object; remove it so storage does not accumulate junk.
    await supabase.storage.from(STORAGE_BUCKETS.assets).remove([storagePath]);
    return { ok: false, error: error?.message ?? "Could not save the image." };
  }

  revalidatePath("/assets");
  return { ok: true, data: { id: data.id, url: `/api/assets/${data.id}/content` } };
}

/** What one generation is assumed to cost. Exposed for the picker's warning copy. */
export async function imageCostEstimate(): Promise<number> {
  return IMAGE_COST_ESTIMATE_USD;
}
