// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, render, screen } from "@testing-library/react";

/**
 * The credit the picker promises.
 *
 * "Photographs from Pexels. The photographer is credited in the asset library."
 * The ingestion wrote `creator_name`, `license_ref` and `original_page_url`,
 * the asset library read none of them, and nothing anywhere credited anybody.
 * A licence obligation discharged only into a database column is not
 * discharged.
 */

// `asset-library.tsx` reaches "@/lib/data/assets" directly and via
// "@/lib/data/upload" — a "use server" file that imports `server-only`.
vi.mock("@/lib/data/assets", () => ({
  updateAssetAlt: vi.fn(),
  deleteAsset: vi.fn(),
  registerAsset: vi.fn(),
}));
vi.mock("next/navigation", () => ({
  useRouter: () => ({ refresh: vi.fn(), push: vi.fn() }),
}));

const { AssetLibrary } = await import("@/components/dashboard/asset-library");

const base = {
  id: "00000000-0000-4000-8000-000000000001",
  kind: "image" as const,
  mimeType: "image/jpeg",
  byteSize: 1024,
  width: 1600,
  height: 900,
  alt: "A harbour at dusk",
  filename: "Ada Lovelace on Pexels",
  createdAt: "2026-01-01T00:00:00Z",
  presentationTitle: null,
  url: "/api/assets/00000000-0000-4000-8000-000000000001/content",
  source: "upload" as "upload" | "stock" | "generated",
  creatorName: null as string | null,
  creatorPageUrl: null as string | null,
  originalPageUrl: null as string | null,
  licenseRef: null as string | null,
  provider: null as string | null,
  model: null as string | null,
  prompt: null as string | null,
};

afterEach(cleanup);

/** Opening the detail dialog is how provenance is reached. */
function open(asset: typeof base) {
  render(<AssetLibrary assets={[asset]} />);
  const card = screen.getByRole("button", { name: new RegExp(asset.filename, "i") });
  act(() => card.click());
}

describe("asset provenance", () => {
  it("credits the photographer of a stock photograph, with its licence", () => {
    open({
      ...base,
      source: "stock",
      creatorName: "Ada Lovelace",
      creatorPageUrl: "https://www.pexels.com/@ada",
      originalPageUrl: "https://www.pexels.com/photo/1",
      licenseRef: "Pexels License",
      provider: "Pexels",
    });
    expect(screen.getByText("Ada Lovelace")).toBeTruthy();
    expect(screen.getByText(/Pexels License/)).toBeTruthy();
    const credit = screen.getByText("Ada Lovelace").closest("a");
    expect(credit?.getAttribute("href")).toBe("https://www.pexels.com/@ada");
    expect(credit?.getAttribute("rel")).toContain("noopener");
  });

  it("still credits a photographer whose profile link is missing", () => {
    open({ ...base, source: "stock", creatorName: "Grace Hopper", provider: "Pexels" });
    expect(screen.getByText("Grace Hopper")).toBeTruthy();
  });

  it("says a generated image was generated, and by what", () => {
    open({ ...base, source: "generated", model: "gpt-image-1", prompt: "a harbour at dusk" });
    expect(screen.getByText(/Generated by gpt-image-1/)).toBeTruthy();
    expect(screen.getByText(/a harbour at dusk/)).toBeTruthy();
  });

  it("says nothing about an upload, because there is nothing to say", () => {
    open(base);
    expect(screen.queryByText(/Photograph by/)).toBeNull();
    expect(screen.queryByText(/Generated/)).toBeNull();
  });
});
